name: resq_alert
description: ResQ Alert demo app
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_messaging: ^15.0.3
  firebase_database: ^11.3.10
  # Notifications / sound / torch
  flutter_local_notifications: ^17.1.2
  audioplayers: ^5.0.4
  torch_light: ^1.1.0

  # Permissions
  permission_handler: ^11.0.1

  # Device info & local storage
  shared_preferences: ^2.1.1
  package_info_plus: ^9.0.0
  connectivity_plus: ^4.0.1
  device_info_plus: ^9.0.0
  # Networking
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/whitelog.png
    - assets/wcc_logo.png
    - assets/help_about_placeholder.png
    - assets/RQ.png
    - assets/res.jpg
    - assets/EmergencyHotlines.jpg
    - assets/sounds/alert_sound.mp3
    - assets/logooo.png