name: resq_alert
description: ResQ Alert demo app
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.7.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.0.3
  firebase_database: ^11.0.3
  firebase_app_check: ^0.3.2+10
  local_auth: ^2.1.0  # or latest
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/whitelog.png
    - assets/wcc_logo.png
    - assets/help_about_placeholder.png
    - assets/em_medical.png
    - assets/em_fire.png
    - assets/em_security.png
    - assets/em_accident.png
    - assets/em_natural.png
    - assets/em_other.png
    - assets/logo.png
    - assets/RQ.png
    - assets/res.jpg
    - assets/EmergencyHotlines.jpg